---
  - name: setup autoboot
    copy: src=haproxy dest=/etc/default/haproxy
  - name: setting up ha proxy config
    template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy