---
  - name: configure default site configurations
    template: src=default.conf dest=/etc/nginx/sites-available/default mode=0644
    notify: restart ngnix services
  - name: copy default page
    template: src=index.html dest=/var/www/html mode=0644