---
  - name: add runner group
    group: 
      name: docker
      state: present
  - name: add dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common    
      state: present
      update_cache: yes
  - name: adding docker Keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add Docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: installing docker
    apt:
      name: docker-ce
      state: present